spring:
  application:
    name: product-service
  zipkin:
    ## 添加zipkin跟踪服务地址
    base-url: http://localhost:9411/
server:
  port: 2221
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


