server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 是否开启自我保护模式，默认为true
    enable-self-preservation: true
    # 清理无效节点的时间间隔
    eviction-interval-timer-in-ms: 10000

    #eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，
    #这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上默认30s
    #responseCacheUpdateInvervalMs: 3000

    #eureka server缓存readWriteCacheMap失效时间，这个只有在这个时间过去后缓存才会失效，失效前不会更新，
    #过期后从registry重新读取注册服务信息，registry是一个ConcurrentHashMap。
    #由于启用了evict其实就用不太上改这个配置了
    #默认180s
    #responseCacheAutoExpirationInSeconds: 180